services:
  - type: web
    name: yandex-competitor-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      bash -c "python -m playwright install --with-deps && uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
